# Generated by Django 4.2.3 on 2023-08-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
