# Generated by Django 4.2.3 on 2023-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='Core.cart'),
        ),
    ]
